# Generated by Django 2.1.5 on 2019-01-21 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='learning_number',
        ),
    ]
