# Generated by Django 2.1.5 on 2019-01-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_course_learning_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('easy', '初级'), ('middle', '中级'), ('higher', '高级')], max_length=4, verbose_name='难度'),
        ),
    ]
